version: '3.8'

services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: MyPostgresDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "5439:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

#  careermate:
#    image: chinh3571113/careermate:1.0.1
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    restart: unless-stopped
